version: "3.9"
services:
  traefik:
    image: traefik:v2.9
    hostname: traefik
    networks:
      - test-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=test-network
      - --entryPoints.web.address=:80

  manager:
    hostname: manager
    build:
      dockerfile: Dockerfile
      context: manager
    networks:
      - test-network
    env_file: .env.manager

  nginx-worker:
    hostname: worker
    env_file:
      - .env.worker
    build:
      dockerfile: Dockerfile
      context: worker
    networks:
      - test-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.worker.rule=PathPrefix(`/`)
      - traefik.http.routers.worker.entryPoints=web
      - traefik.http.services.worker.loadbalancer.server.port=80
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 3
    restart: unless-stopped

networks:
  test-network:
    name: test-network